### ISSUE TITLE
Send message to everyone in a channel (route)

### ISSUE THREAD

**Issue by JhonatanRian** [davidje13/websocket-express#4]
How do I report a message to all users connected to a certain channel (route)?

In my case, I have a redis client subscribed to a pub/sub channel with other applications, when a message arrives in redis I want it to be forwarded to connected users.

**Comment by davidje13** [comment]
that's a bit higher-level than this library, and will depend on your overall architecture (and in particular whether you have load-balancing across multiple servers or are handling all connections for a given topic from a single server)

the abstract way to hook something like a global chat room in with this library would be to set up a pub/sub inside the websocket handler, such as:

```js
const broker = /* some pub/sub handler, either in-memory if load-balancing is not required, or via an external service */;

router.ws('/path', async (req, res, next) => {
  const ws = await res.accept();
  const myID = crypto.randomUUID();

  const subscription = broker.subscribe(({ sender, message }) => {
    if (sender !== myID) {
      ws.send(message);
    }
  });

  ws.on('message', (msg) => {
    broker.dispatch({ sender: myID, message: msg });
  });

  ws.on('close', () => subscription.close());
});
```

As an example, a crude in-memory version of a possible broker would be:

```js
class MyBroker {
  constructor() {
    this.subscribers = new Set();
  }

  subscribe(fn) {
    this.subscribers.add(fn);
    return { close: () => this.subscribers.delete(fn); };
  }

  dispatch(item) {
    for (const fn of this.subscribers) {
      fn(item);
    }
  }
}
```

Obviously this pattern could also be extended in various ways to support distinct channels depending on the URL accessed.
